chore: upload sarif to github

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,6 +40,13 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-gradle-
 
-      - name: Run Detekt
-        run: |
-          ./gradlew clean detekt
+      - name: Run detekt
+        run: ./gradlew detekt
+
+        # Make sure we always run this upload task,
+        # because the previous step may fail if there are findings.
+      - name: Upload SARIF to Github using the upload-sarif action
+        uses: github/codeql-action/upload-sarif@v1
+        if: success() || failure()
+        with:
+          sarif_file: build/detekt.sarif
